### ISSUE TITLE
[Feature Request]  Support Proxy functionality when request the downloading.

### ISSUE THREAD

**Issue by Sraconni** [patrickkfkan/patreon-dl#62]
It would be great if `patreon-dl` could support Proxy functionality (http(s), socks, etc.) and allow customization through the config file. 

Since I occasionally experience unstable connections to Patreon, this would allow download requests to leverage the Proxy server's network instead of relying on my local connection.

**Comment by patrickkfkan** [comment]
My main hurdle in implementing this is having access to a trustworthy proxy server. Would VPN be a valid alternative for you?

**Comment by Sraconni** [comment]
Actually, there's no need to embed a built-in proxy server. Instead, implementing this as a toggleable feature (disabled by default) with proxy server fields left default or blank.

For example: 
```yaml
# Proxy protocol, -1 = NO_PROXY, 0 = HTTP/HTTPS, 1 = SOCKS4, 2 = SOCKS5
proxy.protocol: -1
# Proxy host
proxy.host: 127.0.0.1
# Proxy port
proxy.port: 7890
# Proxy authentication settings
# Whether to enable proxy authentication
proxy.auth.enabled: false
proxy.auth.username: proxy-username
proxy.auth.password: proxy-password
```

Users could enable it and input their proxy details when needed or keep default settings to access local network connection when disabled if not needed.

Regarding using VPNs as an alternative, I've tried this approach but found it unstable due to requiring global proxy settings that inadvertently affect network traffic from other applications. A dedicated proxy option within the patreon-dl would provide more targeted and reliable control.
